### ISSUE TITLE
What about protocols with non colon-slash-slash?

### ISSUE THREAD

**Issue by Arttse** [sindresorhus/prepend-http#3]
Example:

``` javascript
const prependHttp = require('prepend-http');

prependHttp('mailto:info@site.com');
//=> http://mailto:info@site.com

prependHttp('tel:1234567890');
//=> http://tel:1234567890
```

Another example. Module [`normalize-url`](https://github.com/sindresorhus/normalize-url) used this module `prepend-http`, so:

``` javascript
const normalizeUrl = require('normalize-url');

normalizeUrl('mailto:info@site.com');
//=> http://mailto:info@site.com

normalizeUrl('tel:1234567890');
//=> http://tel:1234567890
```

Is this normal or I something do not understand?

**Comment by sindresorhus** [comment]
That's indeed a bug. It should not prepend in those scenarios.

**Comment by Arttse** [comment]
At the moment the only working method that comes to my mind is create list of protocols (non colon-slash-slash), then check out this list. But each time a new protocol is created this type must be added to the list.
